### ISSUE TITLE
Improve GitHub labels

### ISSUE THREAD

**Issue by per1234** [107-systems/107-Arduino-NMEA-Parser#23]
Reference: https://github.com/107-systems/107-Arduino-NMEA-Parser/issues/20#issuecomment-719932632
>@per1234 can you replace the default GitHub labels with others which are a bit more useful? I'd need at least a "Bug Report" and a "Feature Request" label, if you know other labels that make sense then please add them too.

I have a rough idea about a standardized format for labels, as well as how to propagate them across all the repositories. This is a copy/paste from some of my WIP notes, so forgive me if they are not very polished.

Having inconsistent labels the repositories of an organization can make the maintainer's job more difficult as well as making the issue/PR trackers less useful to the users. It can be difficult to interpret the specific meaning of labels and when it is appropriate to apply them.  So having a smaller set of labels to learn is very helpful.

There will be project specific labels that only make sense to have in a specific repository, but there are significant number of core labels that apply to every repository of the organization.

I've been trying to come up with a standardized labeling in my own repositories. I use a `category: item` system. Even though this makes the labels pretty long, it's super nice to have all items for a given category sort together. Both the `arduino/Arduino` and `arduino/arduino-cli` repos are using a similar system to some extent.

This is the list I have so far for my own labels in case they might provide some inspiration:

- conclusion
  - declined
    - This will not be worked on
  - duplicate
    - This issue or pull request already exists
  - invalid
    - Off topic for this repository, or a bug report determined to not actually represent a bug 
- help wanted
  - Assistance from the community is especially welcome
  - Notes:
    - I would prefer put this in the status category, but GitHub has special handling of this label, so I think I should leave it just as `help wanted`, rather than `status: help wanted`.
- priority
  - high
  - low
  - Notes:
    - if no priority label is added, that is "medium"
- status
  - changes requested
  - in progress
  - on hold
  - pending
    - Waiting on action in another project
  - waiting for information
  - blocked
  - moved?
    - I'm ending up moving a lot of issues to Jira, and wishing I had a label to indicate this without needing to look at the issue. However, since GitHub has a transfer system for moving within my repos, I'm not sure how common this is. Probably better to just have it as a local label, or at least not a universal one.
- topic
  - CI
  - code
  - content
    - Notes:
      - Some repos don't contain code, so this could be the equivalent to "code" for those repos
        - example: ino-hardware-package-list, ino-troubleshooting
          - This might seem like "documentation", but I would like "documentation" to be about the documentation for the project, rather than about the content of a project when that content happens to be documentation.
  - documentation
  - metadata?
  - repository maintenance
    - I guess this would be about things like issues, PRs, contributing.md, labels, topics, repo description, wiki
  - structure
    - Notes:
      - this is very vague. I can't even really remember what I intended. Is it about the folder/filename structure of the repository? If so, it could be "repository structure"
- type
  - bug
  - enhancement
  - to-do
    - Notes:
      - I need to clearly define what this is. I thought it might be useful to have a "to-do list" item, but I haven't actually ended up using this much.

It's also important to make sure the labels are clearly documented and their use well defined. GitHub's label description feature can be used to add a short explanation of the meaning of each label.

One thing I found really useful for maintaining the `arduino/Arduino` issue tracker was when we established a policy (https://github.com/arduino/Arduino/issues/8642) of applying the "feature request" or "bug" labels according to to the intention of the user, rather than as a judgement call by the maintainer. I find that issues can almost always be put under one category or the other, and I can almost always filter my searches accordingly.

There is a GitHub Actions action that may be helpful in keeping the universal labels synced across all the repositories: https://github.com/lannonbr/issue-label-manager-action.

I have done some experimentation for my personal repositories with pulling a list of standardized universal labels from a centralized source, merging that with a list of repository-specific labels, and using the action to update the labels according to changes in the list:
```yaml
name: 'Manage repository labels'

on:
  push:
    paths:
      - '.github/workflows/manage-repository-labels.yml'
      - '.github/repository-labels-data/*.json'
  schedule:
    # run every Tuesday at 3 AM UTC
    - cron: '0 3 * * 2'
  workflow_dispatch:

jobs:
  manage-labels:
    runs-on: 'ubuntu-latest'

    env:
      LOCAL_REPOSITORY_LABELS_DATA_INPUTS_FOLDER: '.github/repository-labels-data'
      # Folder under runner.temp that will be used for merging the labels data files
      REPOSITORY_LABELS_DATA_MERGE_FOLDER: 'repository-labels-data'
      # See: https://github.com/lannonbr/issue-label-manager-action#usage
      REPOSITORY_LABELS_DATA_OUTPUT_PATH: '.github/labels.json'

    steps:
      - uses: 'actions/checkout@1.0.0'

      - name: 'Download universal labels file'
        uses: 'carlosperate/download-file-action@v1.0.3'
        with:
          
          file-url: 'https://raw.githubusercontent.com/per1234/GitHub-labels/main/universal-repository-labels.json'
          location: "${{ runner.temp }}/$REPOSITORY_LABELS_DATA_MERGE_FOLDER"

      - name: 'Merge labels data files'
        run: |
          REPOSITORY_LABELS_DATA_MERGE_PATH="${{ runner.temp }}/$REPOSITORY_LABELS_DATA_MERGE_FOLDER"
          cp "$LOCAL_REPOSITORY_LABELS_DATA_INPUTS_FOLDER"/*.json "$REPOSITORY_LABELS_DATA_MERGE_PATH"
          # Merge all data files and output to the final location
          jq -s '.=.|add|.' "$REPOSITORY_LABELS_DATA_MERGE_PATH"/*.json > "$REPOSITORY_LABELS_DATA_OUTPUT_PATH"

      - name: 'Manage labels'
        uses: 'lannonbr/issue-label-manager-action@2.0.0'
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
